# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference

version: 2.1

# Use a package of configuration called an orb.

orbs: 
  cypress: cypress-io/cypress@1

# Declare a dependency on the welcome-orb

welcome: circleci/welcome-orb@0.4.1

# Orchestrate or schedule a set of jobs

workflows:
  build:
    jobs:
      -cypress/run:
        yarn: true

# Name the workflow “welcome”

welcome:

# Run the welcome/run job in its own container

jobs:

- welcome/run